---
title: "Data model"
output: rmarkdown::html_vignette
description: |
  Description of the t3 data model and how initialise it.
vignette: |
  %\VignetteIndexEntry{Data model}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

<div style="text-align: justify">

## R6 reference classes

The t3 process was built under [R’s R6 reference classes](https://r6.r-lib.org/). R6 is an implementation of encapsulated object-oriented programming for R. This style of programming is also sometimes referred to as classical object-oriented programming. An online documentation was available at [https://r6.r-lib.org](https://r6.r-lib.org) and you can find a brief introduction and overview in the chapter 14 of the book “Advanced R” written by Hadley Wickham (online view was available [here](https://adv-r.hadley.nz/index.html)).


Just to sum up, among other things we choose R6 for the t3 process because:

* all the methods, or function/process if you want to match with R's current typology, are encapsulated in a class. You can make anymore mistake when you run a process (for example with functions how doors the same name in two different package).

* you can use the process of inheritance from an existing class to another. All your methods work in synergy and transparency.

* class are defined with attributes and controls are associated to them to ensure data consistency. When a class was built, you could be sure of what you have inside!

* you manipulate class of a data model how represent a vision of reality more understandable. For example, when you manipulate and object of class "trip", this object contains all attributes necessary to define a trip. 

* you can optimise and increase the running speed of your process, especially related to the R's memory usage and the identification of treatments/functions associated.

## Class and methods documentations


All documentation regarding class and methods associated are available thought the navigation bar `Reference` in the section `R6 class`. For example, if you search the main t3 process you can find them in the documentation of the class `full_trip`. This documentation, like the other one, is also available when the call the function help in the R console (for example above `?full_trip`).

</div>
