#' @name standardisedsample
#' @title R6 class standardisedsample
#' @description Create R6 reference object class standardisedsample
#' @importFrom R6 R6Class
#' @importFrom codama r_type_checking
standardisedsample <- R6::R6Class(classname = "standardisedsample",
                                  public = list(
                                    # initialize ----
                                    #' @description Initialize function for R6 standardisedsample class.
                                    #' @param trip_id (character) Trip identification.
                                    #' @param well_id Object of class {\link[base]{character}} expected. Well identification.
                                    #' For the Observe database, the topiaid field from the table ps_logbook.well of the database is used;
                                    #' if it is missing, the well ID is generated by the t3 process, as follows: well_id="fr.ird.data.ps.logbook.Well#trip_id#well_label".
                                    #' For the AVDTH database, well identification is always generated by T3 process such as: well_id="fr.ird.avdth.entities.data.Well#vessel_code#trip_end_date#N_CUVE.F_POS_CUVE" .
                                    #' @param well_id_source Object of class {\link[base]{character}} expected. Source of the well identification: "Observe" if the topiaid field from Observe database is used or "T3" if the the well ID is generated by the t3 process.
                                    #' @param sample_id Object of class {\link[base]{character}} expected. Sample identification.
                                    #' @param sample_quality_code Object of class {\link[base]{integer}} expected. Sample quality identification.
                                    #' @param sample_type_code Object of class {\link[base]{integer}} expected. Sample type identification.
                                    #' @param species_fao_code (character) Specie code identification on 3 characters.
                                    #' @param sample_standardised_length_class_lf Object of class {\link[base]{integer}} expected. Sample standardized length class length fork of measured individuals.
                                    #' @param sample_number_measured_extrapolated_lf Object of class {\link[base]{numeric}} expected. Sample number of measured individuals extrapolated to all counted individuals.
                                    #' @param sample_total_count Object of class {\link[base]{integer}} expected. Sample number of total individuals counted.
                                    initialize = function(trip_id,
                                                          well_id,
                                                          well_id_source,
                                                          sample_id,
                                                          sample_quality_code,
                                                          sample_type_code,
                                                          species_fao_code,
                                                          sample_standardised_length_class_lf,
                                                          sample_number_measured_extrapolated_lf,
                                                          sample_total_count) {
                                      # 1 - Arguments verifications ----
                                      codama::r_type_checking(r_object = trip_id,
                                                              type = "character",
                                                              length = 1L)
                                      codama::r_type_checking(r_object = well_id,
                                                              type = "character",
                                                              length = 1L)
                                      codama::r_type_checking(r_object = well_id_source,
                                                              type = "character",
                                                              length = 1L)
                                      codama::r_type_checking(r_object = sample_id,
                                                              type = "character",
                                                              length = NULL)
                                      codama::r_type_checking(r_object = sample_quality_code,
                                                              type = "integer",
                                                              length = 1L)
                                      codama::r_type_checking(r_object = sample_type_code,
                                                              type = "integer",
                                                              length = 1L)
                                      codama::r_type_checking(r_object = species_fao_code,
                                                              type = "character",
                                                              length = 1L)
                                      codama::r_type_checking(r_object = sample_standardised_length_class_lf,
                                                              type = "integer",
                                                              length = 1L)
                                      codama::r_type_checking(r_object = sample_number_measured_extrapolated_lf,
                                                              type = "numeric",
                                                              length = 1L)
                                      codama::r_type_checking(r_object = sample_total_count,
                                                              type = "integer",
                                                              length = 1L)
                                      # 2 - Attributions ----
                                      private$trip_id <- trip_id
                                      private$well_id <- well_id
                                      private$well_id_source <- well_id_source
                                      private$sample_id <- sample_id
                                      private$sample_quality_code <- sample_quality_code
                                      private$sample_type_code <- sample_type_code
                                      private$species_fao_code <- species_fao_code
                                      private$sample_standardised_length_class_lf <- sample_standardised_length_class_lf
                                      private$sample_number_measured_extrapolated_lf <- sample_number_measured_extrapolated_lf
                                      private$sample_total_count <- sample_total_count
                                    }),
                                  private = list(
                                    trip_id = NULL,
                                    well_id = NULL,
                                    well_id_source = NULL,
                                    sample_id = NULL,
                                    sample_quality_code = NULL,
                                    sample_type_code = NULL,
                                    species_fao_code = NULL,
                                    sample_standardised_length_class_lf = NULL,
                                    sample_number_measured_extrapolated_lf = NULL,
                                    sample_total_count = NULL))
