on:
  push:
    branches:
    - master
    - doc-test-level-1
    - development

name: build and deploy gh-pages

jobs:
  pkgdown:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.fork == false
    runs-on: ubuntu-latest
    env:
      RSPM: https://packagemanager.rstudio.com/cran/__linux__/bionic/latest
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      isPush: ${{ github.event_name == 'push' }}

    steps:
          - uses: actions/checkout@v2

          - name: Install R
            uses: r-lib/actions/setup-r@v1
            with:
              r-version: '4.0.0'

          - name: Install java
            uses: actions/setup-java@v1
            with:
              java-version: '9.0.4' # The JDK version to make available on the path.
              java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
              architecture: x64 # (x64 or x86) - defaults to x64
              
          - name: Configurate java
            run: |
              sudo R CMD javareconf

          - uses: r-lib/actions/setup-pandoc@v1
          
          - uses: r-lib/actions/setup-tinytex@v1

          - name: Install pak and query dependencies
            run: |
              install.packages("pak", repos = "https://r-lib.github.io/p/pak/dev/")
              saveRDS(pak::pkg_deps("local::.", dependencies = TRUE), ".github/r-depends.rds")
            shell: Rscript {0}
          
          - name: Install furdeb
            run: |
              Sys.getenv("JAVA_HOME")
              Sys.setenv(JAVA_HOME = "/usr/lib/jvm/adoptopenjdk-8-hotspot-amd64/jre/lib/amd64/server")
              pak::pkg_install("OB7-IRD/furdeb")
            shell: Rscript {0}

          - name: Cache R packages
            uses: actions/cache@v2
            with:
              path: ${{ env.R_LIBS_USER }}
              key: ubuntu-18.04-${{ steps.install-r.outputs.installed-r-version }}-1-${{ hashFiles('.github/r-depends.rds') }}
              restore-keys: ubuntu-18.04-${{ steps.install-r.outputs.installed-r-version }}-1-

          - name: Install system dependencies
            if: runner.os == 'Linux'
            run: |
              pak::local_system_requirements(execute = TRUE)
              pak::pkg_system_requirements("pkgdown", execute = TRUE)
            shell: Rscript {0}

          - name: Install dependencies
            run: |
              pak::local_install_dev_deps(upgrade = TRUE)
              pak::pkg_install("pkgdown")
            shell: Rscript {0}

          - name: Install package
            run: R CMD INSTALL .

          - name: Build and deploy pkgdown site
            if: contains(env.isPush, 'true')
            run: |
              git config --local user.name "$GITHUB_ACTOR"
              git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
              Rscript -e 'pkgdown::deploy_to_branch(new_process = FALSE)'
